FROM node:22-alpine AS build
WORKDIR /web
COPY apps/web/package.json /web/package.json
RUN npm install
COPY apps/web /web
RUN npm run build

FROM nginx:1.27-alpine
COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /web/dist /usr/share/nginx/html
EXPOSE 80
